// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OrangeEventHitboxes","status":true,"description":"Allows the configuration of custom hitboxes for events","parameters":{}},
{"name":"MVCommons","status":false,"description":"Great utility library that provides common-use and\nsimplified functions. Also expands default classes.","parameters":{}}
];
